In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set()

In [4]:
data = pd.read_csv("colondataset2.csv")

In [5]:
data.shape

(62, 2002)

In [6]:
data.head()

Unnamed: 0     H55933     R39465    R39465_     R85482     U14973  \
0           1  8589.4160  5468.2407  4263.4077  4064.9358  1997.8930   
1           2  9164.2540  6719.5293  4883.4487  3718.1590  2015.2214   
2           3  3825.7050  6970.3613  5369.9688  4705.6500  1166.5536   
3           4  6246.4487  7823.5340  5955.8350  3975.5642  2002.6132   
4           5  3230.3286  3694.4500  3400.7400  3463.5857  2181.4202   

      R02593     T51496     H80240     T65938  ...    R70790     L11706  \
0  5282.3250  2169.7200  2773.4211  7526.3860  ...  67.56125  259.91250   
1  5569.9070  3849.0588  2793.3875  7017.7340  ...  92.23875   96.27625   
2  1572.1678  1325.4025  1472.2587  3296.9512  ...  82.71500   31.10250   
3  2130.5430  1531.1425  1714.6312  3869.7850  ...  41.68375    5.92500   
4  2922.7820  2069.2463  2948.5750  3303.3710  ...  76.60375  161.35000   

      T90549    D17390     M33210     H18490     H40891    R77780    T49647  \
0  138.89874  88.23250   39.66786   67.82875   75.67750  83.52250  28.70125   
1  150.59000  82.23750   85.03333  152.19500  186.56750  44.47250  16.77375   
2  193.92000  76.97250  224.62024   31.22500   42.65625  16.09250  15.15625   
3  183.00626  74.52875   67.71072   48.33875   42.52000  49.98250  16.08500   
4   61.70125  54.56375  223.35953   73.09875   57.59875   7.48875  31.81250   

      Class  
0  Abnormal  
1    Normal  
2  Abnormal  
3    Normal  
4  Abnormal  

[5 rows x 2002 columns]

In [7]:
data.isnull().values.any()

False

In [8]:
cnt=0#STRING
for i in data:
    for j in data[i]:
        if(type(j) == str):
            cnt+=1
        else:
            pass
print(cnt)

62


In [9]:
for i in data:
    try:
        data[i] = data[i].astype('float32')
    except:
        print(i)#NOT ABLE TO CONVERT TO FLOAT/INT

Class


In [10]:
le = preprocessing.LabelEncoder()

In [11]:
res = le.fit(data['Class'])
res = le.transform(data['Class'])

In [12]:
data['Class'] = res

In [13]:
cnt=0#STRING
for i in data:
    for j in data[i]:
        if(type(j) == str):
            cnt+=1
        else:
            pass
print(cnt)

0


In [14]:
X = data.drop(['Class'],axis=1)
y = data['Class']

In [15]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [17]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.25, random_state=42)

In [18]:
sel = SelectFromModel(RandomForestClassifier(n_estimators = 12000))
sel.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(n_estimators=12000))

In [19]:
sel.get_support()

array([False, False, False, ..., False, False,  True])

In [20]:
selected_feat= X_train.columns[(sel.get_support())]
len(selected_feat)

380

In [21]:
print(selected_feat)


Index(['H20709', 'U14971', 'T52342', 'T95018', 'T61609', 'T62220', 'T57619',
       'T58861', 'T61661', 'T93094',
       ...
       'R62945', 'U05040', 'T60778', 'T57468', 'M64110', 'T89666', 'D38551',
       'D14689', 'H40891', 'Class'],
      dtype='object', length=380)


In [23]:
import sys
import numpy as np
np.set_printoptions(threshold=np.inf)
print(selected_feat)
np.array(selected_feat)

Index(['H20709', 'U14971', 'T52342', 'T95018', 'T61609', 'T62220', 'T57619',
       'T58861', 'T61661', 'T93094',
       ...
       'R62945', 'U05040', 'T60778', 'T57468', 'M64110', 'T89666', 'D38551',
       'D14689', 'H40891', 'Class'],
      dtype='object', length=380)


array(['H20709', 'U14971', 'T52342', 'T95018', 'T61609', 'T62220',
       'T57619', 'T58861', 'T61661', 'T93094', 'U12255', 'T48804',
       'T71025', 'T51534', 'T61661_', 'H55758', 'X55715', 'H05803',
       'T68848', 'T72938', 'R50158', 'T52185', 'T53396', 'T63370',
       'R78934', 'T72889', 'T72175', 'U12255_', 'T51529', 'R49974_',
       'D25217', 'M26697', 'T65003', 'D21261', 'R28373', 'R34698',
       'M86553', 'H70425', 'X57351', 'T52342_', 'T57780', 'T94579',
       'D14662', 'T57686', 'T55558', 'T51023', 'D63874', 'L28010',
       'Z24727', 'L16510', 'M64445', 'X17042_', 'T50334_', 'M36981',
       'R82938', 'M76378', 'M63391', 'U20982', 'U37012', 'H80975',
       'M16937', 'M26252', 'M76378_', 'D14520', 'T53694', 'K03460',
       'T79152', 'H64489', 'X15183', 'M86400', 'T55248', 'M65028',
       'T59406', 'R70030', 'T57780_', 'T72503', 'M83751', 'X14958',
       'T70058', 'Z50753', 'T56940', 'T54341', 'R73052', 'D31885',
       'U30825', 'R38636', 'X87159', 'H25136', 'T60155

In [25]:
v=data.columns

In [27]:
d=data[['H20709', 'U14971', 'T52342', 'T95018', 'T61609', 'T62220',
       'T57619', 'T58861', 'T61661', 'T93094', 'U12255', 'T48804',
       'T71025', 'T51534', 'T61661_', 'H55758', 'X55715', 'H05803',
       'T68848', 'T72938', 'R50158', 'T52185', 'T53396', 'T63370',
       'R78934', 'T72889', 'T72175', 'U12255_', 'T51529', 'R49974_',
       'D25217', 'M26697', 'T65003', 'D21261', 'R28373', 'R34698',
       'M86553', 'H70425', 'X57351', 'T52342_', 'T57780', 'T94579',
       'D14662', 'T57686', 'T55558', 'T51023', 'D63874', 'L28010',
       'Z24727', 'L16510', 'M64445', 'X17042_', 'T50334_', 'M36981',
       'R82938', 'M76378', 'M63391', 'U20982', 'U37012', 'H80975',
       'M16937', 'M26252', 'M76378_', 'D14520', 'T53694', 'K03460',
       'T79152', 'H64489', 'X15183', 'M86400', 'T55248', 'M65028',
       'T59406', 'R70030', 'T57780_', 'T72503', 'M83751', 'X14958',
       'T70058', 'Z50753', 'T56940', 'T54341', 'R73052', 'D31885',
       'U30825', 'R38636', 'X87159', 'H25136', 'T60155', 'L10284',
       'T52343', 'H41129', 'M94556', 'T59878', 'M90104', 'H40560',
       'D00761', 'R87126', 'H20426', 'M22382', 'T56604', 'T95048',
       'T57483', 'H65182', 'M94630', 'H24401', 'M33680', 'T48014',
       'R46753', 'R42501', 'J04794', 'T51571', 'R15447', 'T99478',
       'R73660', 'D16431', 'T73092', 'H67764', 'H89087', 'M28129',
       'X12671', 'T60318', 'M85289', 'U02493', 'R10066', 'T62972',
       'X68277', 'X70944', 'T51849', 'X06614_', 'M88279', 'T51261',
       'D49396', 'M34175', 'M22490', 'D00763', 'M69135', 'X12369',
       'T78104', 'T54276', 'M76378__', 'H87465', 'H24030', 'H40095',
       'R01755', 'D13627', 'M83667', 'H26419', 'J04621', 'R88740',
       'X70326', 'X15882', 'M94132', 'Z49269', 'T92451', 'Z49269_',
       'R75843', 'U29092', 'T59162', 'X66975', 'T54360', 'R33367',
       'H27202', 'X72018', 'H43887', 'H11719', 'L13939', 'T63539',
       'T93284', 'M96233', 'L38503', 'L13042', 'T54364', 'H87473',
       'X81372', 'T50321', 'T86473', 'J04026', 'H40137', 'T90280',
       'X12466', 'X15880', 'J03161_', 'R08183', 'T53889', 'L24203',
       'R36977', 'M22632', 'X01060', 'M80815', 'U09564', 'Y00097',
       'X69141', 'T70062', 'X05610', 'L08069', 'D31716', 'M81635',
       'R97912', 'J03004', 'T55840', 'T56690', 'M34175_', 'L27476',
       'R84411', 'M84349', 'L41142', 'U04953', 'H80114', 'M37583',
       'D00762', 'D13315_', 'H65355', 'H72965', 'R96357', 'T92259',
       'T83361', 'R62549', 'T96873', 'X74295', 'T75577', 'U22055',
       'R67358', 'T40454', 'M92843', 'X12496', 'D16294', 'H23544',
       'H62828', 'D78152', 'D14665', 'T84481', 'H20512', 'T95046',
       'R32804', 'X70040', 'T47377', 'M94203', 'R39209', 'H72234',
       'X83301', 'U24166', 'T62947', 'X68688', 'M31303', 'M26683',
       'Z11502', 'R44052', 'X75208', 'M92287', 'R39209_', 'H02540',
       'L05144', 'H10925', 'R56399', 'U26312', 'X86809', 'H77597',
       'R11485', 'R64115', 'M28882', 'J02854', 'M34175__', 'T84049',
       'D15049', 'M18216', 'L32977', 'D00860', 'L41559', 'R54097',
       'R45529', 'D13665', 'U10324', 'T47778', 'X86693', 'M14539',
       'R46362', 'Z25521', 'R59202', 'T47719', 'M34344', 'H63361',
       'X74330', 'T67406', 'R42127', 'T61333', 'T51493', 'H11084',
       'X53799', 'R06601', 'R49459', 'R08021', 'H81558', 'M31516',
       'T79831', 'R60877', 'X63629', 'X13482', 'T58645', 'T47383',
       'L06132', 'M88108', 'T51539', 'T94993', 'H66786', 'T83368',
       'M36634', 'R52081', 'K02268', 'L05485', 'R80427', 'T86749',
       'R99935', 'H87135', 'X16663', 'H79136', 'M82919', 'M26383',
       'D42047', 'T67077', 'D00596', 'X53586', 'H16991', 'X60489',
       'X54942', 'X17025', 'T54303', 'T94350', 'X73902', 'U17899',
       'J05032', 'H08393', 'T50797', 'M22050', 'U10362', 'X68314',
       'R41873', 'M85079', 'U21090', 'M27190', 'Z22936', 'T90668',
       'M55265', 'U14631', 'X07290', 'H06524', 'X89985', 'U32519',
       'H55916', 'L07648', 'H49515', 'R44301', 'M84721', 'U25138',
       'X07767', 'M76558', 'U19969', 'U37673_', 'X56597', 'X54941',
       'R16156', 'M91463', 'J04102', 'H64807', 'U36621', 'X62048',
       'R67999', 'D29808', 'T78323', 'M35531', 'R62945', 'U05040',
       'T60778', 'T57468', 'M64110', 'T89666', 'D38551', 'D14689',
       'H40891']]

In [28]:
d

H20709       U14971        T52342        T95018       T61609  \
0   1181.630005  2417.958252   3139.399902   3192.413086  1643.557495   
1   3630.382568  1906.213135   5745.395996   2796.083252  1351.964966   
2    855.455017   802.304749   3251.108398   1444.096436   591.808777   
3   1789.670044  1587.791748   3496.145752   2342.382080  1392.716187   
4   2285.308838  2576.748779   3056.725098   3350.502441  2648.267578   
5   3466.791260  2137.417969   2716.379150   1788.146362  1227.418701   
6   1364.170044  2093.501221   3048.079102   3116.195312  2194.072510   
7   3616.246094  1673.226196   4623.079102   1752.553589  1013.618774   
8   3334.284912  5329.664062   1547.216675   6264.492676  4410.262695   
9   5729.321289  2763.322510   5865.658203   1769.333252  2092.195068   
10  3648.427490  5570.308105   8512.029297   9309.401367  6470.862305   
11  6074.589844  3723.878662   3353.466797   3548.396484  2782.461182   
12  2609.572510  2711.746338   3462.904297   4384.365723  2243.116211   
13  3216.153809  2676.371338   4670.895996   3524.439209  1968.228760   
14  2555.937500  3371.301270   4847.662598   6432.073730  3146.756104   
15  2464.192383  3904.840576   2767.295898   6187.467773  3494.702393   
16  1290.420044  4205.417969   1872.000000   5521.620117  2849.117432   
17  2445.211182  1834.091675   4361.504395   1030.178589  1150.122559   
18  2166.385010  3095.998779   2177.312500   4610.957031  3175.820068   
19  5161.138672  2910.638184   4113.712402   1812.971436  1531.344971   
20  1356.323853  1931.616699   5822.575195   3263.116699  1402.817505   
21  2411.462402  1821.229858   8844.992188   2041.327393  1300.359985   
22  2543.699951  5571.278809   3060.570801   5261.339355  4601.676270   
23  1421.717529  1243.748779    758.529175    590.352356   538.690002   
24  3915.723877  6517.921387   6189.924805   9026.375977  4989.442383   
25  1128.493774  1528.397583   2448.758301   2461.891602  1588.813843   
26  1181.288818  1728.367920   2961.733398   2444.138184  1440.680054   
27  3193.873779  4816.358398   5862.687500   8041.295410  4498.676270   
28  2399.063721  3481.251221   8076.116699   5440.052246  2857.978760   
29  2664.587402  4316.296387   7631.149902   6794.704590  4260.627441   
..          ...          ...           ...           ...          ...   
32  2917.370117  3900.642822   3104.808350   5881.081055  3464.523682   
33  3550.688721  4788.104980   4712.154297   5626.590332  2834.356201   
34  1593.457520  1925.352417   2389.991699   3247.456055  1745.722534   
35  2332.237549  3030.451172   2043.370850   5217.500000  3098.431152   
36  1333.772461  2712.971436   5104.262695   4268.071289  2660.843750   
37  2490.741211  3483.597656   2124.083252   6775.803711  4448.227539   
38  3547.257568  2164.836914   4331.966797   2527.882080  1408.221191   
39  2582.011230  4021.484619   3437.204102   6483.604980  3520.167480   
40  1842.416260  1772.258301   1588.391724   3229.722656  1346.312500   
41  4583.193848  2665.513184   4444.958496   2633.576172  1299.708740   
42  7127.011230  3681.710693   7727.612305   4436.532227  3214.007568   
43  5455.745117  5455.885742   7722.433105   6788.575195  6446.696289   
44  4986.591309  3753.816650  10694.516602   4830.351074  2618.806152   
45  6879.555176  6581.255859   6469.808105  11454.709961  6563.618652   
46  5247.567383  6136.100098   8252.908203   6789.401367  8193.987305   
47  4707.586426  2050.558350   6173.100098   2073.551270  1190.316284   
48  2263.236084  1327.664307   3513.733398   1752.408325   849.094971   
49  5976.108887  2555.620117   6192.387695   5584.450195  2496.169922   
50  2953.297607  1865.298828   4524.529297   5670.297363  3990.584961   
51  7860.928711  7190.996582   4295.820801  12061.599609  7018.532715   
52  3242.042480  3491.618896   2595.537598   6046.312988  2956.523682   
53  5320.093750  3043.689209   5520.966797   4263.899902  1976.908813   
54  1895.812500   938.959534   3531.579102   3509.093994  1155.8613

In [36]:
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split(d, y, test_size = 0.25, random_state = 0) 


In [37]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(xtrain, ytrain) 

GaussianNB()

In [38]:
y_pred = gnb.predict(xtest) 

In [39]:
confusion_matrix(ytest, y_pred)

array([[11,  3],
       [ 0,  2]])

In [40]:
from sklearn.metrics import accuracy_score 
print (" Navie Bayes Accuracy : ", accuracy_score(ytest, y_pred)) 


 Navie Bayes Accuracy :  0.8125


In [41]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(xtrain,ytrain)
y_pred=clf.predict(xtest)

In [42]:
from sklearn.metrics import accuracy_score 
print ("Random Forest Accuracy : ", accuracy_score(ytest, y_pred)) 


Random Forest Accuracy :  0.875


In [43]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(xtrain, ytrain)

SVC(kernel='linear')

In [44]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
clf = OneVsRestClassifier(svm.SVC(gamma=0.01, C=100., probability=True, class_weight='balanced', kernel='linear'))
clf.fit(xtrain, ytrain)
y_pred=clf.predict(xtest)

In [45]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(ytest,y_pred))
print(classification_report(ytest,y_pred))

0.8125
              precision    recall  f1-score   support

           0       0.92      0.86      0.89        14
           1       0.33      0.50      0.40         2

    accuracy                           0.81        16
   macro avg       0.63      0.68      0.64        16
weighted avg       0.85      0.81      0.83        16



In [46]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

In [47]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate, max_features=2, max_depth = 2, random_state = 0)
    gb.fit(xtrain, ytrain)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(xtrain, ytrain)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(xtest, ytest)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.978
Accuracy score (validation): 0.812

Learning rate:  0.1
Accuracy score (training): 1.000
Accuracy score (validation): 0.812

Learning rate:  0.25
Accuracy score (training): 1.000
Accuracy score (validation): 0.875

Learning rate:  0.5
Accuracy score (training): 1.000
Accuracy score (validation): 0.812

Learning rate:  0.75
Accuracy score (training): 1.000
Accuracy score (validation): 0.875

Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (validation): 0.812



In [48]:
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 0.5, max_features=2, max_depth = 2, random_state = 0)
gb.fit(xtrain, ytrain)
predictions = gb.predict(xtest)

print("Confusion Matrix:")
print(confusion_matrix(ytest, predictions))
print()
print("Classification Report")
print(classification_report(ytest, predictions))
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(ytest, predictions)) 

Confusion Matrix:
[[12  2]
 [ 1  1]]

Classification Report
              precision    recall  f1-score   support

           0       0.92      0.86      0.89        14
           1       0.33      0.50      0.40         2

    accuracy                           0.81        16
   macro avg       0.63      0.68      0.64        16
weighted avg       0.85      0.81      0.83        16

Accuracy :  0.8125


In [49]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier 
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(xtrain,ytrain)

#Predict the response for test dataset
y_pred = clf.predict(xtest)

In [50]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest, y_pred)

array([[9, 5],
       [1, 1]])

In [51]:
from sklearn.metrics import accuracy_score 
print ("Accuracy decision: ", accuracy_score(ytest, y_pred)) 

Accuracy decision:  0.625
