In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set()

In [3]:
data = pd.read_csv("colondataset2.csv")

In [4]:
data.shape

(62, 2002)

In [5]:
data.head()

Unnamed: 0     H55933     R39465    R39465_     R85482     U14973  \
0           1  8589.4160  5468.2407  4263.4077  4064.9358  1997.8930   
1           2  9164.2540  6719.5293  4883.4487  3718.1590  2015.2214   
2           3  3825.7050  6970.3613  5369.9688  4705.6500  1166.5536   
3           4  6246.4487  7823.5340  5955.8350  3975.5642  2002.6132   
4           5  3230.3286  3694.4500  3400.7400  3463.5857  2181.4202   

      R02593     T51496     H80240     T65938  ...    R70790     L11706  \
0  5282.3250  2169.7200  2773.4211  7526.3860  ...  67.56125  259.91250   
1  5569.9070  3849.0588  2793.3875  7017.7340  ...  92.23875   96.27625   
2  1572.1678  1325.4025  1472.2587  3296.9512  ...  82.71500   31.10250   
3  2130.5430  1531.1425  1714.6312  3869.7850  ...  41.68375    5.92500   
4  2922.7820  2069.2463  2948.5750  3303.3710  ...  76.60375  161.35000   

      T90549    D17390     M33210     H18490     H40891    R77780    T49647  \
0  138.89874  88.23250   39.66786   67.82875   75.67750  83.52250  28.70125   
1  150.59000  82.23750   85.03333  152.19500  186.56750  44.47250  16.77375   
2  193.92000  76.97250  224.62024   31.22500   42.65625  16.09250  15.15625   
3  183.00626  74.52875   67.71072   48.33875   42.52000  49.98250  16.08500   
4   61.70125  54.56375  223.35953   73.09875   57.59875   7.48875  31.81250   

      Class  
0  Abnormal  
1    Normal  
2  Abnormal  
3    Normal  
4  Abnormal  

[5 rows x 2002 columns]

In [6]:
data.isnull().values.any()

False

In [7]:
cnt=0#STRING
for i in data:
    for j in data[i]:
        if(type(j) == str):
            cnt+=1
        else:
            pass
print(cnt)

62


In [8]:
for i in data:
    try:
        data[i] = data[i].astype('float32')
    except:
        print(i)#NOT ABLE TO CONVERT TO FLOAT/INT

Class


In [9]:
le = preprocessing.LabelEncoder()

In [10]:
res = le.fit(data['Class'])
res = le.transform(data['Class'])

In [11]:
data['Class'] = res

In [12]:
cnt=0#STRING
for i in data:
    for j in data[i]:
        if(type(j) == str):
            cnt+=1
        else:
            pass
print(cnt)

0


In [14]:
X = data.drop(['Class'],axis=1)
y = data['Class']

In [15]:
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = 0) 


In [16]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(xtrain, ytrain) 

GaussianNB()

In [17]:
y_pred = gnb.predict(xtest) 

In [18]:
confusion_matrix(ytest, y_pred)

array([[10,  4],
       [ 0,  2]])

In [19]:
from sklearn.metrics import accuracy_score 
print (" Navie Bayes Accuracy : ", accuracy_score(ytest, y_pred)) 


 Navie Bayes Accuracy :  0.75


In [20]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(xtrain,ytrain)
y_pred=clf.predict(xtest)

In [21]:
from sklearn.metrics import accuracy_score 
print ("Random Forest Accuracy : ", accuracy_score(ytest, y_pred)) 


Random Forest Accuracy :  0.875


In [22]:
knn = KNeighborsClassifier(n_neighbors=12, metric='euclidean')
knn.fit(xtrain, ytrain)

KNeighborsClassifier(metric='euclidean', n_neighbors=12)

In [23]:
y_pred = knn.predict(xtest)

In [24]:
from sklearn.metrics import accuracy_score 
print ("KNN Accuracy : ", accuracy_score(ytest, y_pred)) 


KNN Accuracy :  1.0


In [25]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(xtrain, ytrain)

SVC(kernel='linear')

In [26]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
clf = OneVsRestClassifier(svm.SVC(gamma=0.01, C=100., probability=True, class_weight='balanced', kernel='linear'))
clf.fit(xtrain, ytrain)
y_pred=clf.predict(xtest)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(ytest,y_pred))
print(classification_report(ytest,y_pred))

0.75
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.00      0.00      0.00         2

    accuracy                           0.75        16
   macro avg       0.43      0.43      0.43        16
weighted avg       0.75      0.75      0.75        16



In [28]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

In [29]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate, max_features=2, max_depth = 2, random_state = 0)
    gb.fit(xtrain, ytrain)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(xtrain, ytrain)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(xtest, ytest)))
    print()

Learning rate:  0.05
Accuracy score (training): 1.000
Accuracy score (validation): 0.812

Learning rate:  0.1
Accuracy score (training): 1.000
Accuracy score (validation): 0.750

Learning rate:  0.25
Accuracy score (training): 1.000
Accuracy score (validation): 0.750

Learning rate:  0.5
Accuracy score (training): 1.000
Accuracy score (validation): 0.625

Learning rate:  0.75
Accuracy score (training): 1.000
Accuracy score (validation): 0.812

Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (validation): 0.688



In [30]:
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 0.5, max_features=2, max_depth = 2, random_state = 0)
gb.fit(xtrain, ytrain)
predictions = gb.predict(xtest)

print("Confusion Matrix:")
print(confusion_matrix(ytest, predictions))
print()
print("Classification Report")
print(classification_report(ytest, predictions))
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(ytest, predictions)) 

Confusion Matrix:
[[8 6]
 [0 2]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      0.57      0.73        14
           1       0.25      1.00      0.40         2

    accuracy                           0.62        16
   macro avg       0.62      0.79      0.56        16
weighted avg       0.91      0.62      0.69        16

Accuracy :  0.625


In [31]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier 
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(xtrain,ytrain)

#Predict the response for test dataset
y_pred = clf.predict(xtest)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest, y_pred)

array([[9, 5],
       [1, 1]])

In [33]:
from sklearn.metrics import accuracy_score 
print ("Accuracy decision: ", accuracy_score(ytest, y_pred)) 

Accuracy decision:  0.625


In [31]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import numpy as numpy 



In [32]:
scaler= StandardScaler()
scaler.fit(xtrain)
xtrain= scaler.transform(xtrain)
xtest= scaler.transform(xtest)

In [33]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
K_cent= 5
km= KMeans(n_clusters= K_cent, max_iter= 1000)
km.fit(xtrain)
cent= km.cluster_centers_

In [34]:
from sklearn.metrics import accuracy_score
import math
max=0 
for i in range(K_cent):
	for j in range(K_cent):
		d= numpy.linalg.norm(cent[i]-cent[j])
		if(d> max):
			max= d
d= max

sigma= d/math.sqrt(2*K_cent)

In [35]:
shape= xtrain.shape
row= shape[0]
column= K_cent
G= numpy.empty((row,column), dtype= float)
for i in range(row):
    for j in range(column):
        dist= numpy.linalg.norm(xtrain[i]-cent[j])
        G[i][j]= math.exp(-math.pow(dist,2)/math.pow(2*sigma,2))

In [36]:
GTG= numpy.dot(G.T,G)
GTG_inv= numpy.linalg.inv(GTG)
fac= numpy.dot(GTG_inv,G.T)
W= numpy.dot(fac,ytrain)

In [37]:
row= xtest.shape[0]
column= K_cent
G_test= numpy.empty((row,column), dtype= float)
for i in range(row):
	for j in range(column):
		dist= numpy.linalg.norm(xtest[i]-cent[j])
		G_test[i][j]= math.exp(-math.pow(dist,2)/math.pow(2*sigma,2))

In [38]:
prediction= numpy.dot(G_test,W)
prediction= 0.5*(numpy.sign(prediction-0.5)+1)

score= accuracy_score(prediction,ytest)
print(score)

0.875


In [39]:
print("FINAL RESULT")
Algorithm=['NB','KNN','DT','RF','SVM','GBT']
Without_feature_selection=['74','100','56.25`','87.86','75','77.77']
titles = ['Algorithm', 'Without FS']
data = [titles] + list(zip(Algorithm,Without_feature_selection))
for i, d in enumerate(data):
    line = '|'.join(str(x).ljust(12) for x in d)
    print(line)
    if i == 0:
        print('-' * len(line))
print("RBF:87.5")

FINAL RESULT
Algorithm   |Without FS  
-------------------------
NB          |74          
KNN         |100         
DT          |56.25`      
RF          |87.86       
SVM         |75          
GBT         |77.77       
RBF:87.5
