In [17]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn import preprocessing
import warnings

In [18]:
warnings.filterwarnings('ignore')

In [19]:
data = pd.read_csv("finalDataSet.csv")

In [20]:
data.shape

(799, 16384)

In [21]:
le = preprocessing.LabelEncoder()#tTO CONVERT STRINGS TO NUMBERS AS WE CANNOT FORM DATASET USING STRINGS(PATENT ID,CLASS/)
pid = le.fit(data['Patient Id'])
pid = le.transform(data['Patient Id'])

In [22]:
res = le.fit(data['Class'])
res = le.transform(data['Class'])

In [23]:
data['Patient Id'] = pid
data['Class'] = res

In [24]:
data.isnull().values.any()

True

In [25]:
cnt=0#STRING
for i in data:
    for j in data[i]:
        if(type(j) == str):
            cnt+=1
        else:
            pass
print(cnt)

2334


In [26]:
for i in data:
    try:
        data[i] = data[i].astype('float32')
    except:
        print(i)#NOT ABLE TO CONVERT TO FLOAT/INT

gene_1
gene_2
gene_3
gene_6
gene_11
gene_12
gene_19
gene_29
gene_1318
gene_1329
gene_1331
gene_1334
gene_1335
gene_1445
gene_1447
gene_1449
gene_1451
gene_1455
gene_1457
gene_1461
gene_1462
gene_1464
gene_3237
gene_3244
gene_3246
gene_3248
gene_3249
gene_3251
gene_3254
gene_3256
gene_3258
gene_3318
gene_3998
gene_4003
gene_5019
gene_5020
gene_5021
gene_5027
gene_5273
gene_5274
gene_5279
gene_5281
gene_5283
gene_5285
gene_5287
gene_7239
gene_7241
gene_7242
gene_7245
gene_7249
gene_7256
gene_10593
gene_10597
gene_10598
gene_10599
gene_10600
gene_10603
gene_10604
gene_10605
gene_10606
gene_10607
gene_10608
gene_10609
gene_10610


In [27]:
ls=['gene_1',
'gene_2',
'gene_3',
'gene_6',
'gene_11',
'gene_12',
'gene_19',
'gene_29',
'gene_1318',
'gene_1329',
'gene_1331',
'gene_1334',
'gene_1335',
'gene_1445',
'gene_1447',
'gene_1449',
'gene_1451',
'gene_1455',
'gene_1457',
'gene_1461',
'gene_1462',
'gene_1464',
'gene_3237',
'gene_3244',
'gene_3246',
'gene_3248',
'gene_3249',
'gene_3251',
'gene_3254',
'gene_3256',
'gene_3258',
'gene_3318',
'gene_3998',
'gene_4003',
'gene_5019',
'gene_5020',
'gene_5021',
'gene_5027',
'gene_5273',
'gene_5274',
'gene_5279',
'gene_5281',
'gene_5283',
'gene_5285',
'gene_5287',
'gene_7239',
'gene_7241',
'gene_7242',
'gene_7245',
'gene_7249',
'gene_7256',
'gene_10593',
'gene_10597',
'gene_10598',
'gene_10599',
'gene_10600',
'gene_10603',
'gene_10604',
'gene_10605',
'gene_10606',
'gene_10607',
'gene_10608',
'gene_10609',
'gene_10610']

In [28]:
for i in ls:
    print(data[i].dtype)
    #data[i] = data[i].astype('float32')#THESE COLUMNS CONTAIN MULTIPLE TYPES(STRING,INT,FLOAT)

object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object


In [29]:
sym = ['!','@','#', '$', '^', '&', '*','.','?','<','>','.',";", "'",'"']#CHECKING FOR SPECIAL CHARACTERS
cnt = 0
for i in ls:
    for j in data[i]:
        try:
            if(j in sym or type(j) == str or j == '?'):
                try:
                    data[i] = data[i].replace({j: float(j)})#TRYING TO CONVERT TO FLOAT 
                except:
                    data[i] = data[i].replace({j: 'NaN'})#IF NOT,REPLACING THEM WITH NULL
                    cnt+=1
        except:
            pass

print(cnt)

72


In [30]:
clm=[]
for i in data:
    clm.append(i)

In [31]:
for i in ls:
    print(data[i].dtype)

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
object


In [32]:
X = data.drop('Class', axis = 1)
x = X
del x['Patient Id']
x

gene_0    gene_1    gene_2     gene_3     gene_4  gene_5    gene_6  \
0    0.000000  2.017209  3.265527   5.478487  10.431999     0.0  7.175175   
1    0.000000  0.592732  1.588421   7.586157   9.623011     0.0  6.816049   
2    0.000000  3.511759  4.327199   6.881787   9.870730     0.0  6.972130   
3    0.000000  3.663618  4.507649   6.659068  10.196184     0.0  7.843375   
4    0.000000  2.655741  2.821547        NaN   9.738265     0.0  6.566967   
5    0.000000  3.467853  3.581918   6.620243   9.706829     0.0  7.758510   
6    0.000000  1.224966  1.691177   6.572007   9.640511     0.0  6.754888   
7    0.000000  2.854853  1.750478   7.226720   9.758691     0.0  5.952103   
8    0.000000  3.992125  2.772730   6.546692  10.488252     0.0       NaN   
9    0.000000  3.642494  4.423558   6.849511   9.464466     0.0  7.947216   
10   0.000000  3.492071  3.553373   7.151707  10.253446     0.0  8.301258   
11   0.000000  2.941181  2.663276   6.516897   9.376292     0.0  7.860323   
12   0.000000  3.970348  2.364292   7.145443   9.240605     0.0  7.810758   
13   0.000000  1.551048  3.529846   6.326825  10.633849     0.0  8.944659   
14   0.000000  1.964842  2.183010   6.596832  10.248141     0.0  7.087251   
15   0.000000  2.901379  3.685368   6.669665   9.999098     0.0  6.948834   
16   0.000000  3.460913  3.618474   5.661048   9.731217     0.0  8.435591   
17   0.000000  3.004519  3.007178  25.000000   9.062661     0.0  7.995937   
18   0.000000  1.541465  2.541540   6.843255   9.444468     0.0  5.479091   
19   0.000000  4.167583  3.841389   6.976123   9.982252     0.0  6.977372   
20   0.000000  2.066916  2.619953   6.757997  11.123940     0.0  5.415674   
21   0.000000       NaN  2.976712   6.038416   9.437973     0.0  5.893828   
22   0.000000  1.131853  2.351515   6.845841   9.196860     0.0  7.853827   
23   0.000000  3.121844  2.473943   7.119616  10.732490     0.0  5.506031   
24   0.000000  4.801852  2.648465   6.009255   9.611917     0.0       NaN   
25   0.341758  4.317702  3.642678   6.790003   8.435999     0.0  8.573628   
26   0.000000  2.325242  3.247092   8.174007  10.065053     0.0  7.487446   
27   0.000000  0.657091  1.026304   5.411196   9.601388     0.0  6.263874   
28   0.000000  3.670081  3.382792   7.581939   9.386658     0.0  7.140523   
29   0.000000  5.688295  4.899949  10.129528  10.093695     0.0  7.389902   
..        ...       ...       ...        ...        ...     ...       ...   
769  0.000000  3.028056  2.514552   6.301622   9.497151     0.0  6.617021   
770  0.000000  2.706995  3.574586   6.090422   9.557619     0.0  7.162452   
771  0.000000  3.683427  4.158555   5.976767  10.272548     0.0  6.695660   
772  0.000000  2.566888  2.370583   6.459294   9.874400     0.0  7.332430   
773  0.000000  3.280006  3.607425   5.659805  10.064864     0.0  7.436253   
774  0.000000  2.542852  2.020235   5.083098  10.328428     0.0  4.852848   
775  0.000000  1.584337  2.610629   6.813538   9.368515     0.0  7.574790   
776  0.000000  0.000000  2.316406   6.510695   9.932384     0.0  6.442733   
777  0.000000  0.792022  2.542010   6.286147   9.183747     0.0  9.758661   
778  0.000000  3.834731  1.894372   6.314852  10.964370     0.0  7.437053   
779  0.000000  3.482255  3.064952   6.699288  10.134182     0.0  5.946555   
780  0.000000  1.693944  2.605139   6.487568   9.533067     0.0  7.762987   
781  0.000000  1.499527  3.213254   6.873949   9.091655     0.0  4.812057   
782  0.000000  3.031942  2.575554   6.403079  10.485024     0.0  7.549723   
783  0.000000  2.060705  3.719830   6.427137  10.432187     0.0  8.353760   
784  0.000000  2.656016  1.746958   6.641060  10.519164     0.0  6.808140   
785  0.000000  2.752963  1.960549   5.748145  10.248912     0.0  7.487173   
786  0.000000  2.364460  3.180689   6.745049   9.499660     0.0  6.455861   
787  0.000000  4.315436  4.398385   6.273313  10.346890     0.0  7.770809   
788  0.000000  4.869200  4.087717   6.369039   9.684506     0.0  7.929903   
789

In [33]:
y = data['Class']
y

0      4.0
1      3.0
2      4.0
3      4.0
4      0.0
5      4.0
6      2.0
7      4.0
8      0.0
9      4.0
10     0.0
11     2.0
12     4.0
13     0.0
14     0.0
15     0.0
16     3.0
17     2.0
18     2.0
19     4.0
20     0.0
21     2.0
22     3.0
23     0.0
24     2.0
25     3.0
26     1.0
27     0.0
28     0.0
29     0.0
      ... 
769    0.0
770    0.0
771    3.0
772    0.0
773    3.0
774    2.0
775    0.0
776    3.0
777    2.0
778    3.0
779    3.0
780    3.0
781    2.0
782    0.0
783    4.0
784    0.0
785    0.0
786    2.0
787    0.0
788    4.0
789    2.0
790    0.0
791    0.0
792    0.0
793    0.0
794    4.0
795    3.0
796    0.0
797    3.0
798    1.0
Name: Class, Length: 799, dtype: float32

In [34]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#from sklearn.preprocessing import Imputer
#imputer=Imputer(missing_values = np.nan,strategy='mean', axis=0,verbose=0)
imputer.fit(x)
x = imputer.transform(x)
x

array([[0.        , 2.01720929, 3.26552691, ..., 0.        , 9.29193306,
        0.84092641],
       [0.        , 0.5927321 , 1.58842082, ..., 1.59081757, 3.46740985,
        1.17804527],
       [0.        , 3.51175898, 4.32719872, ..., 0.        , 5.53370953,
        0.22589186],
       ...,
       [0.        , 1.86564173, 2.71819721, ..., 0.49692246, 4.95514059,
        3.21768045],
       [0.        , 3.94295546, 4.45380727, ..., 7.07921791, 4.48480844,
        5.78779793],
       [0.        , 3.24958187, 3.70749166, ..., 6.82536602, 7.56745434,
        2.47547412]])

In [35]:
np.savetxt("test_array1.csv",x,delimiter=",")

In [37]:
column_names=list(data.columns)[1:len(list(data.columns))-1]

In [38]:
test_df=pd.DataFrame(x,columns=column_names)

In [39]:
test_df

gene_0    gene_1    gene_2     gene_3     gene_4  gene_5    gene_6  \
0    0.000000  2.017209  3.265527   5.478487  10.431999     0.0  7.175175   
1    0.000000  0.592732  1.588421   7.586157   9.623011     0.0  6.816049   
2    0.000000  3.511759  4.327199   6.881787   9.870730     0.0  6.972130   
3    0.000000  3.663618  4.507649   6.659068  10.196184     0.0  7.843375   
4    0.000000  2.655741  2.821547   6.744767   9.738265     0.0  6.566967   
5    0.000000  3.467853  3.581918   6.620243   9.706829     0.0  7.758510   
6    0.000000  1.224966  1.691177   6.572007   9.640511     0.0  6.754888   
7    0.000000  2.854853  1.750478   7.226720   9.758691     0.0  5.952103   
8    0.000000  3.992125  2.772730   6.546692  10.488252     0.0  7.403477   
9    0.000000  3.642494  4.423558   6.849511   9.464466     0.0  7.947216   
10   0.000000  3.492071  3.553373   7.151707  10.253446     0.0  8.301258   
11   0.000000  2.941181  2.663276   6.516897   9.376292     0.0  7.860323   
12   0.000000  3.970348  2.364292   7.145443   9.240605     0.0  7.810758   
13   0.000000  1.551048  3.529846   6.326825  10.633849     0.0  8.944659   
14   0.000000  1.964842  2.183010   6.596832  10.248141     0.0  7.087251   
15   0.000000  2.901379  3.685368   6.669665   9.999098     0.0  6.948834   
16   0.000000  3.460913  3.618474   5.661048   9.731217     0.0  8.435591   
17   0.000000  3.004519  3.007178  25.000000   9.062661     0.0  7.995937   
18   0.000000  1.541465  2.541540   6.843255   9.444468     0.0  5.479091   
19   0.000000  4.167583  3.841389   6.976123   9.982252     0.0  6.977372   
20   0.000000  2.066916  2.619953   6.757997  11.123940     0.0  5.415674   
21   0.000000  3.011646  2.976712   6.038416   9.437973     0.0  5.893828   
22   0.000000  1.131853  2.351515   6.845841   9.196860     0.0  7.853827   
23   0.000000  3.121844  2.473943   7.119616  10.732490     0.0  5.506031   
24   0.000000  4.801852  2.648465   6.009255   9.611917     0.0  7.403477   
25   0.341758  4.317702  3.642678   6.790003   8.435999     0.0  8.573628   
26   0.000000  2.325242  3.247092   8.174007  10.065053     0.0  7.487446   
27   0.000000  0.657091  1.026304   5.411196   9.601388     0.0  6.263874   
28   0.000000  3.670081  3.382792   7.581939   9.386658     0.0  7.140523   
29   0.000000  5.688295  4.899949  10.129528  10.093695     0.0  7.389902   
..        ...       ...       ...        ...        ...     ...       ...   
769  0.000000  3.028056  2.514552   6.301622   9.497151     0.0  6.617021   
770  0.000000  2.706995  3.574586   6.090422   9.557619     0.0  7.162452   
771  0.000000  3.683427  4.158555   5.976767  10.272548     0.0  6.695660   
772  0.000000  2.566888  2.370583   6.459294   9.874400     0.0  7.332430   
773  0.000000  3.280006  3.607425   5.659805  10.064864     0.0  7.436253   
774  0.000000  2.542852  2.020235   5.083098  10.328428     0.0  4.852848   
775  0.000000  1.584337  2.610629   6.813538   9.368515     0.0  7.574790   
776  0.000000  0.000000  2.316406   6.510695   9.932384     0.0  6.442733   
777  0.000000  0.792022  2.542010   6.286147   9.183747     0.0  9.758661   
778  0.000000  3.834731  1.894372   6.314852  10.964370     0.0  7.437053   
779  0.000000  3.482255  3.064952   6.699288  10.134182     0.0  5.946555   
780  0.000000  1.693944  2.605139   6.487568   9.533067     0.0  7.762987   
781  0.000000  1.499527  3.213254   6.873949   9.091655     0.0  4.812057   
782  0.000000  3.031942  2.575554   6.403079  10.485024     0.0  7.549723   
783  0.000000  2.060705  3.719830   6.427137  10.432187     0.0  8.353760   
784  0.000000  2.656016  1.746958   6.641060  10.519164     0.0  6.808140   
785  0.000000  2.752963  1.960549   5.748145  10.248912     0.0  7.487173   
786  0.000000  2.364460  3.180689   6.745049   9.499660     0.0  6.455861   
787  0.000000  4.315436  4.398385   6.273313  10.346890     0.0  7.770809   
788  0.000000  4.869200  4.087717   6.369039   9.684506     0.0  7.929903   
789

In [40]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(test_df, y, test_size=0.25, random_state=42)

In [41]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train, y_train) 
y_pred = gnb.predict(X_test) 

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[76,  0,  4,  1,  0],
       [ 1,  9,  0,  8,  0],
       [ 2,  0, 25,  2,  0],
       [11,  0,  2, 27,  0],
       [ 1,  0,  0,  0, 31]])

In [43]:
from sklearn.metrics import accuracy_score 
print ("Accuracy NB: ", accuracy_score(y_test, y_pred)) 


Accuracy NB:  0.84


In [50]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=27, metric='euclidean')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [51]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[81,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 29,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 32]])

In [52]:
from sklearn.metrics import accuracy_score 
print ("Accuracy knn: ", accuracy_score(y_test, y_pred)) 

Accuracy knn:  1.0


In [53]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier 
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [54]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[81,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 29,  0,  0],
       [ 0,  2,  0, 38,  0],
       [ 0,  0,  0,  0, 32]])

In [55]:
from sklearn.metrics import accuracy_score 
print ("Accuracy decision: ", accuracy_score(y_test, y_pred)) 

Accuracy decision:  0.99


In [56]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=5)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [57]:
confusion_matrix(y_test, y_pred)

array([[80,  1,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  1, 28,  0,  0],
       [ 0,  0,  1, 39,  0],
       [ 0,  0,  0,  0, 32]])

In [58]:
from sklearn.metrics import accuracy_score 
print ("Accuracy Random forest: ", accuracy_score(y_test, y_pred)) 


Accuracy Random forest:  0.985


In [59]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
clf = OneVsRestClassifier(svm.SVC(gamma=0.001, C=10., probability=True, class_weight='balanced', kernel='linear'))
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

In [60]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred)) 


Accuracy :  1.0


In [61]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

In [62]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate, max_features=2, max_depth = 2, random_state = 0)
    gb.fit(X_train, y_train)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(X_test, y_test)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.873
Accuracy score (validation): 0.765

Learning rate:  0.1
Accuracy score (training): 0.973
Accuracy score (validation): 0.890

Learning rate:  0.25
Accuracy score (training): 0.988
Accuracy score (validation): 0.945

Learning rate:  0.5
Accuracy score (training): 1.000
Accuracy score (validation): 0.965

Learning rate:  0.75
Accuracy score (training): 1.000
Accuracy score (validation): 0.960

Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (validation): 0.925



In [63]:
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 0.5, max_features=2, max_depth = 2, random_state = 0)
gb.fit(X_train, y_train)
predictions = gb.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))
print()
print("Classification Report")
print(classification_report(y_test, predictions))
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, predictions)) 

Confusion Matrix:
[[80  0  0  1  0]
 [ 1 17  0  0  0]
 [ 1  0 27  1  0]
 [ 1  0  1 38  0]
 [ 1  0  0  0 31]]

Classification Report
              precision    recall  f1-score   support

         0.0       0.95      0.99      0.97        81
         1.0       1.00      0.94      0.97        18
         2.0       0.96      0.93      0.95        29
         3.0       0.95      0.95      0.95        40
         4.0       1.00      0.97      0.98        32

    accuracy                           0.96       200
   macro avg       0.97      0.96      0.96       200
weighted avg       0.97      0.96      0.96       200

Accuracy :  0.965
