In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set()

In [2]:
data = pd.read_csv("dataset3leu.csv")

In [3]:
data.shape

(71, 7129)

In [4]:
data.head()

ALL  -1.533621735  -1.235672925  -0.333982875  0.488702121  -1.300893264  \
0  ALL     -0.867610     -1.275501      0.375927     0.444011     -1.229660   
1  ALL     -0.433172     -1.184492     -0.459196     0.436264     -1.325882   
2  ALL     -1.671903     -1.596424     -1.422571     0.193353     -1.818329   
3  ALL     -1.187689     -1.335256     -0.797493     0.235632     -1.311206   
4  ALL     -1.127234     -1.113730     -1.362768    -0.360312     -1.513975   

   -1.682668245  -2.010994928  -1.449185684  0.035344171  ...  0.385566637.10  \
0     -1.642072      0.572919     -1.588304     0.219574  ...       -0.158356   
1     -1.407264     -0.264655     -1.147713    -0.573541  ...        0.662728   
2     -1.744469     -1.793197     -1.446178    -0.325815  ...        0.161918   
3     -1.654381     -1.441690     -1.058556    -0.582683  ...        0.176721   
4     -1.777619      0.824113     -1.237939    -0.348518  ...       -0.181902   

   1.268787786.1  -0.217953576.26  0.25538086.19  -1.057940081.19  \
0       0.822880        -1.369024       0.542521        -0.796527   
1       0.642714        -0.466828       0.856140        -0.416816   
2       0.462715        -0.585185      -0.181008        -0.611257   
3       0.750758        -0.380081       0.526298        -0.888026   
4       1.317042        -0.835275       0.603224        -0.644228   

   1.295991951.1  0.733853066.6  -0.301622172.30  0.133657104.16  \
0      -0.218494       0.378380        -0.663166       -0.663166   
1       1.132893       0.475669        -0.530138        1.566946   
2       1.113077       0.148928        -0.625945        0.871972   
3       0.719203       0.419502        -0.487514        0.358999   
4       1.490610       1.000031        -0.172972        0.080430   

   -0.825595612.23  
0        -0.611045  
1        -0.805978  
2        -1.037246  
3        -0.742858  
4        -0.670192  

[5 rows x 7129 columns]

In [5]:
data = data.dropna()

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
res = le.fit(data['ALL'])
res = le.transform(data['ALL'])

In [8]:
data['ALL'] = res

In [9]:
data.isnull().values.any()

False

In [10]:
X = data.drop(['ALL'],axis=1)
y = data['ALL']

In [11]:
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = 0) 


In [12]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(xtrain, ytrain) 

GaussianNB()

In [13]:
y_pred = gnb.predict(xtest) 

In [14]:
confusion_matrix(ytest, y_pred)

array([[9, 0],
       [2, 7]])

In [15]:
from sklearn.metrics import accuracy_score 
print (" Navie Bayes Accuracy : ", accuracy_score(ytest, y_pred)) 


 Navie Bayes Accuracy :  0.8888888888888888


In [16]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(xtrain,ytrain)
y_pred=clf.predict(xtest)

In [17]:
from sklearn.metrics import accuracy_score 
print ("Random Forest Accuracy : ", accuracy_score(ytest, y_pred)) 


Random Forest Accuracy :  0.8888888888888888


In [18]:
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(xtrain, ytrain)

KNeighborsClassifier(metric='euclidean')

In [19]:
y_pred = knn.predict(xtest)

In [20]:
from sklearn.metrics import accuracy_score 
print ("KNN Accuracy : ", accuracy_score(ytest, y_pred)) 


KNN Accuracy :  0.9444444444444444


In [21]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(xtrain, ytrain)

SVC(kernel='linear')

In [22]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
clf = OneVsRestClassifier(svm.SVC(gamma=0.01, C=100., probability=True, class_weight='balanced', kernel='linear'))
clf.fit(xtrain, ytrain)
y_pred=clf.predict(xtest)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(ytest,y_pred))
print(classification_report(ytest,y_pred))

0.9444444444444444
              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      0.89      0.94         9

    accuracy                           0.94        18
   macro avg       0.95      0.94      0.94        18
weighted avg       0.95      0.94      0.94        18



In [24]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

In [25]:
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate, max_features=2, max_depth = 2, random_state = 0)
    gb.fit(xtrain, ytrain)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(xtrain, ytrain)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(xtest, ytest)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.887
Accuracy score (validation): 0.500

Learning rate:  0.1
Accuracy score (training): 1.000
Accuracy score (validation): 0.611

Learning rate:  0.25
Accuracy score (training): 1.000
Accuracy score (validation): 0.778

Learning rate:  0.5
Accuracy score (training): 1.000
Accuracy score (validation): 0.889

Learning rate:  0.75
Accuracy score (training): 1.000
Accuracy score (validation): 0.722

Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (validation): 0.889



In [26]:
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 0.5, max_features=2, max_depth = 2, random_state = 0)
gb.fit(xtrain, ytrain)
predictions = gb.predict(xtest)

print("Confusion Matrix:")
print(confusion_matrix(ytest, predictions))
print()
print("Classification Report")
print(classification_report(ytest, predictions))
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(ytest, predictions)) 

Confusion Matrix:
[[9 0]
 [2 7]]

Classification Report
              precision    recall  f1-score   support

           0       0.82      1.00      0.90         9
           1       1.00      0.78      0.88         9

    accuracy                           0.89        18
   macro avg       0.91      0.89      0.89        18
weighted avg       0.91      0.89      0.89        18

Accuracy :  0.8888888888888888


In [27]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier 
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(xtrain,ytrain)

#Predict the response for test dataset
y_pred = clf.predict(xtest)

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest, y_pred)

array([[8, 1],
       [6, 3]])

In [29]:
from sklearn.metrics import accuracy_score 
print ("Accuracy decision: ", accuracy_score(ytest, y_pred)) 

Accuracy decision:  0.6111111111111112


In [30]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import numpy as numpy 



In [31]:
scaler= StandardScaler()
scaler.fit(xtrain)
xtrain= scaler.transform(xtrain)
xtest= scaler.transform(xtest)

In [32]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
K_cent= 5
km= KMeans(n_clusters= K_cent, max_iter= 1000)
km.fit(xtrain)
cent= km.cluster_centers_

In [33]:
from sklearn.metrics import accuracy_score
import math
max=0 
for i in range(K_cent):
	for j in range(K_cent):
		d= numpy.linalg.norm(cent[i]-cent[j])
		if(d> max):
			max= d
d= max

sigma= d/math.sqrt(2*K_cent)

In [38]:
xtrain.shape

(53, 7128)

In [34]:
shape= xtrain.shape
row= shape[0]
column= K_cent
G= numpy.empty((row,column), dtype= float)
for i in range(row):
    for j in range(column):
        dist= numpy.linalg.norm(xtrain[i]-cent[j])
        G[i][j]= math.exp(-math.pow(dist,2)/math.pow(2*sigma,2))

In [35]:
GTG= numpy.dot(G.T,G)
GTG_inv= numpy.linalg.inv(GTG)
fac= numpy.dot(GTG_inv,G.T)
W= numpy.dot(fac,ytrain)

In [36]:
row= xtest.shape[0]
column= K_cent
G_test= numpy.empty((row,column), dtype= float)
for i in range(row):
	for j in range(column):
		dist= numpy.linalg.norm(xtest[i]-cent[j])
		G_test[i][j]= math.exp(-math.pow(dist,2)/math.pow(2*sigma,2))

In [37]:
prediction= numpy.dot(G_test,W)
prediction= 0.5*(numpy.sign(prediction-0.5)+1)

score= accuracy_score(prediction,ytest)
print(score)

0.7777777777777778


In [42]:
print("FINAL RESULT")
Algorithm=['NB','KNN','DT','RF','SVM','GBT']
Without_feature_selection=['88.88','94.46','61.1','88.86','94.44','77.77']
titles = ['Algorithm', 'Without FS']
data = [titles] + list(zip(Algorithm,Without_feature_selection))
for i, d in enumerate(data):
    line = '|'.join(str(x).ljust(12) for x in d)
    print(line)
    if i == 0:
        print('-' * len(line))


FINAL RESULT
Algorithm   |Without FS  
-------------------------
NB          |88.88       
KNN         |94.46       
DT          |61.1        
RF          |88.86       
SVM         |94.44       
GBT         |77.77       
